In [1]:
import numpy as np
import pickle
import cv2
from keras.preprocessing.image import img_to_array
from sklearn.preprocessing import LabelBinarizer



default_image_size = tuple((256, 256))


Using TensorFlow backend.


In [14]:
def convert_image_to_array(image_dir):
    try:
        image = cv2.imread(image_dir)
        if image is not None :
            image = cv2.resize(image, default_image_size) 
            print('image', image)
            return img_to_array(image)
        else :
            return np.array([])
    except Exception as e:
        print(f"Error : {e}")
        return None



In [15]:
fileobject = open('cnn_model.pkl', 'rb')
model = pickle.load(fileobject)
imgpath='potato__healthy.jpeg'


In [16]:
imar = convert_image_to_array(imgpath)
#print('imar', imar)
npimagelist = np.array([imar], dtype=np.float16) / 225.0
#print('npimagelist', npimagelist)


image [[[147 140 161]
  [120 113 134]
  [118 111 132]
  ...
  [136 130 149]
  [133 127 146]
  [129 123 142]]

 [[ 97  90 111]
  [139 132 153]
  [168 161 182]
  ...
  [139 133 152]
  [137 131 150]
  [134 128 147]]

 [[132 125 146]
  [139 132 153]
  [125 118 139]
  ...
  [139 133 152]
  [138 132 151]
  [136 130 149]]

 ...

 [[152 145 160]
  [174 167 182]
  [163 156 171]
  ...
  [155 145 158]
  [164 154 167]
  [175 165 178]]

 [[179 172 187]
  [168 161 176]
  [182 175 190]
  ...
  [168 158 171]
  [154 144 157]
  [140 130 143]]

 [[189 182 197]
  [176 169 184]
  [180 173 188]
  ...
  [172 162 175]
  [148 138 151]
  [122 112 125]]]
imar [[[147. 140. 161.]
  [120. 113. 134.]
  [118. 111. 132.]
  ...
  [136. 130. 149.]
  [133. 127. 146.]
  [129. 123. 142.]]

 [[ 97.  90. 111.]
  [139. 132. 153.]
  [168. 161. 182.]
  ...
  [139. 133. 152.]
  [137. 131. 150.]
  [134. 128. 147.]]

 [[132. 125. 146.]
  [139. 132. 153.]
  [125. 118. 139.]
  ...
  [139. 133. 152.]
  [138. 132. 151.]
  [136. 130. 1

In [13]:
PREDICTEDCLASSES2 = model.predict(npimagelist)
print(PREDICTEDCLASSES2)


[[6.0540093e-03 2.7965129e-05 8.7222620e-09 4.1387736e-08 9.9292141e-01
  1.7614219e-11 2.3912531e-08 1.5094177e-10 1.2893986e-12 2.2474051e-06
  2.1706064e-11 5.7275741e-07 6.3949135e-10 9.9365413e-04 1.8971959e-10]]


In [6]:
label_classes = ['Pepper__bell___Bacterial_spot', 'Pepper__bell___healthy',
 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy',
 'Tomato_Bacterial_spot', 'Tomato_Early_blight', 'Tomato_Late_blight',
 'Tomato_Leaf_Mold', 'Tomato_Septoria_leaf_spot',
 'Tomato_Spider_mites_Two_spotted_spider_mite', 'Tomato__Target_Spot',
 'Tomato__Tomato_YellowLeaf__Curl_Virus', 'Tomato__Tomato_mosaic_virus',
 'Tomato_healthy']


In [7]:
max_index = np.argmax(PREDICTEDCLASSES2, axis=1)

print(label_classes[max_index[0]])


Potato___healthy
